api_platform:
  title: DAHU
  version: 0.8.2
  formats:
    jsonld: [ 'application/json' ]
    json: [ 'application/json' ]
  docs_formats:
    jsonld: [ 'application/json' ]
    jsonapi: [ 'application/json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
  defaults:
    pagination_items_per_page: 100
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header