vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    photos:
      uri_prefix: /images/photos
      upload_destination: '%kernel.project_dir%/../../../Front end/dahu/src/assets/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer